---
title: "ReadME"
author: "Bobby Sims"
date: '`r Sys.Date()`'
output: html_document
---

ReadME for Microarray Analysis Project

Differential gene expression analysis of Gene Expression Omnibus dataset from Pohar et.al (2022) 
Transcriptome analysis of Tregs (CD4+Foxp3+) and Tcons (CD4+Foxp3-) from spleen and CNS of naïve mice and at the peak of EAE

In the original study, Pohar et al investigated the therapeutic potential of the adoptive transfer of antigen specific T regulatory cells in treatment of  the neuro inflammatory disease experimental autoimmune encephalitis (EAE) in mice. Baseline characterization of non-treatment, wild type state investigated differential expression profiles of conventional (Tconv) and regulatory (Treg) CD4 T-cells in homeostatic (Naive) and inflammatory (EAE) states. 

Tconv-- general pool of CD4+ FoxP3 - helper T-cells that do not express characteristic  FoxP3 whose functions are generally pro inflammatory
Treg – CD4+ FoxP3+ regulatory cells that play an anti-inflammatory role in the adaptive immune response
The study’s 20 samples fall into 6 groups:
Naïve (healthy)
Group 1:Naïve spleen derived conventional T-cells I’ve named TconvN_Sp (3 Biological replicates)
Group2: Naïve spleen derived T regulatory cells=TregN_Sp (3 Biological replicates)
EAE (Disease)
Group 3: EAE spleen derived conventional T-cells=TconvEAE_Sp (4 Biological replicates)
Group 4: EAE spleen derived T regulatory cells=TregEAE_Sp (3 Biological replicates)
Group 5: EAE CNS derived regulatory T-cells= TregEAE_CNS (3 biological replicates
Group 6: EAE CNS derived conventional T-cells =TconvEAE_CNS (3 biological replicates)

Spleen derived Naïve Treg and Tconv cells represented non-disease homeostatic profiles.
Spleen derived and CNS Treg and Tconv represented systemic and localized neuroinflammatory profiles in EAE respectively.




My analysis focuses on DEG of 5 group comparisons:

TregN_Sp vs TconvN_Sp--Baseline non disease Naïve state DGE between splenic regulatory and conventional CD4 T-cells
 Asks “how much do the two lineages originally differ in non-inflammatory conditions?”
TregEAE_Sp vsTregN_Sp – DGE between splenic Tregs in normal and disease state

TregEAE_CNS vs TregN_Sp—DGE between CNS EAE (Disease focal point) vs Spleen (Naïve, Healthy) Tregs in normal and disease state

TregEAE_CNS vs TregEAE_Sp—DGE between Treg populations during peak EAE in two physiological niches: the focal point in the CNS and the germinal secondary lymphoid tissues.
Asks, “How do Tregs differ across inflammation focal and distal sites during peak CNS inflammation?”
TconvEAE_CNS vs TconvN_Sp—DGE between CNS EAE (Disease focal point) vs Spleen (Naïve, Healthy) Tconv

Plots
Top 5 Up and downregulated genes filtered by Log2 fold change and adjusted p-value
highlighted on Volcano plot and MA plot
PCA
Group variances are visualized 
of all 45101 genes across 6 T cell phenotypes, Naïve (control) and EAE (disease)

GSEA
•	How does differential gene expression among observed groups align with canonical functional expression pathway?
•	Groups used (only 2 contrasts from study)
         Tregs: CNS EAE (Disease focal point) vs Spleen (Naïve, Healthy)
          vs Murine Inflammatory Response Pathway 
   
     Tconv: CNS EAE (Disease focal point) vs Spleen (Naïve, Healthy)
          vs Murine Inflammatory Response Pathway 
WP_INFLAMMATORY_RESPONSE_PATHWAY  

Packages
Indicated in accompanying R script

Other resources

Tutorials
Microarray Data analysis in R:
Bioinformagician

GSEA analysis:
Bioinformatics squid

ChatGpt4 was used for R script code workshopping , feedback and course correction
GeneCards
GSEA Molecular signatures database

References:

1)	Pohar, J., O'Connor, R., Manfroi, B., El-Behi, M., Jouneau, L., Boudinot, P., Bunse, M., Uckert, W., Luka, M., Ménager, M., Liblau, R., Anderton, S. M., & Fillatreau, S. (2022). Antigen receptor-engineered Tregs inhibit CNS autoimmunity in cell therapy using nonredundant immune mechanisms in mice. European journal of immunology, 52(8), 1335–1349. https://doi.org/10.1002/eji.202249845

2)	Liu, G., & Liu, F. (2022). Bach2: A Key Regulator in Th2-Related Immune Cells and Th2 Immune Response. Journal of immunology research, 2022, 2814510. https://doi.org/10.1155/2022/2814510

3)	Newton, R., Priyadharshini, B., & Turka, L. A. (2016). Immunometabolism of regulatory T cells. Nature immunology, 17(6), 618–625. https://doi.org/10.1038/ni.3466

4)	Kurelic, R., Krieg, P. F., Sonner, J. K., Bhaiyan, G., Ramos, G. C., Frantz, S., Friese, M. A., & Nikolaev, V. O. (2021). Upregulation of Phosphodiesterase 2A Augments T Cell Activation by Changing cGMP/cAMP Cross-Talk. Frontiers in pharmacology, 12, 748798. https://doi.org/10.3389/fphar.2021.748798

